### ISSUE TITLE
Bootstrap integration

### ISSUE THREAD

**Issue by chuckhendo** [unumux/willow#41]
I've created a branch for us to explore Bootstrap grid integration. It currently works (I've tried changing layout/row/column classes to their Bootstrap counterparts) and all is good, other than some adjustment in width on the page. Commit is here: 2f4a643c1a

These are the things I can currently recognize that we'll need to do if we want to move forward with this.

- [ ] Determine how we want to import this stuff since it's just a library we imported (currently being imported at the top of the main styles file)
- [ ] Translate variables for width (we have our own variable names, such as $content-max-width). We need to translate these in Willow to Bootstrap's variable names. Need them for all media queries
- [ ] Determine how to handle documentation - Bootstrap documentation will always be up to date, but we don't want to confuse people on what is available (we're only importing grid). Do we want to copy/paste their documentation for grid? Is that allowed under their licensing?
- [ ] We made a few modifiers for rows in order to handle some edge cases. Are these needed in the Bootstrap world? If so, how do we handle them?

/cc @slkennedy @Keale2

**Comment by slkennedy** [comment]
Initial thoughts:
Importing: I think the dependency in Willow is fine. It could instead be a dependency in a Theme but I think Willow makes more sense to me since then the bootstrap features would be available for use with component styles if we go that route. 

Variables: So we'd just add these to our theme variables I think... Not sure if this is all the variables we need to be concerned with but adding this list here as a starting point - https://v4-alpha.getbootstrap.com/layout/grid/#variables

Documentation: I'd like to avoid copying in their docs from a maintenance pov, but I also worry about future updates to bootstrap - if we don't update then the docs may not line up with what we have available. 

Modifiers: From what I can tell yes we still need a modifier to give or take away margin bottom from a row and a modifier to make a row grow to fill the vertical space.   We also need to add to the styling of the container class to make the row grow option work. Example using additional classes:

```scss
.container {
    min-height: 100vh;
}

.row {
    margin-bottom: space(2);

    &.no-margin-bottom {
        margin-bottom: 0;
    }
    
    &.flex-grow {
        flex-grow: 1;
    }
}
```

**Comment by slkennedy** [comment]
The latest version of Willow adds Bootstrap and I think we handled all the above points/questions.  Thanks @chuckhendo for the outline.
