### ISSUE TITLE
W3C Validation

### ISSUE THREAD

**Issue by chuckhendo** [unumux/willow#48]
Do we want to consider sending our HTML through W3C validation? For example, on primary-nav, the validator throws a warning that `role="navigation"` is not required for `<nav>` elements. I'm not sure if that's something we want to "fix" or not, but I wanted to make sure everyone is aware.

This is probably pretty low priority; obviously doesn't break anything. But if anyone using Willow is running a validator on their code, it might raise red flags that our code is causing warnings/errors. 

/cc @slkennedy @dbay24 @Keale2

**Comment by slkennedy** [comment]
We've run the components through the validator in the past and saw that same issue. Left the role attr in because we didn't find anything saying to definitely leave it off.  This doc says to use it to improve accessibility for agents that have aria support and for agents that don't support HTML5. But then it also says as support for HTML5 increases we MAY be able to remove it.  So nothing definitive - https://www.w3.org/WAI/GL/wiki/Using_HTML5_nav_element

Testing screen readers without the role but leaving the aria-label: `<nav aria-label="primary">`
NVDA and VoiceOver are handling this well.  VO announces "navigation primary", NVDA says "primary navigation"

So this issue seems up to us.

As for validation in general would love a way to have this be included in Oak.  Have you ever used anything to do that check during development? I found this but haven't used it before - https://github.com/htacg/tidy-html5

**Comment by chuckhendo** [comment]
We do need something in Oak, but probably also need something specific for this repo. We can create a custom gulpfile to do linting and whatnot specifically for this, and use it as a test condition for pull requests. Can't really use Oak directly on this repo due to it not actually needing to compile anything for this

**Comment by slkennedy** [comment]
Sounds good. Have any thoughts on what we should do about `role="navigation"`?

**Comment by chuckhendo** [comment]
Do we have any sort of screen reader support standards, similar to how we have browser support standards?

**Comment by slkennedy** [comment]
I know we recommend some on the accessibility site but not sure we have any standards. @dbay24

**Comment by dbay24** [comment]
We don't currently have any defined per screen reader, that is something we will need to take some time and develop. For now we just supply a list of tools and resources including JAWS, NVDA, and the mac screen reader, nothing specifically pertaining to one or the other from a requirements point of view.

**Comment by chuckhendo** [comment]
I would suggest that if the code works properly in the screen readers we recommend, we can probably drop the `role="navigation"`.  But we can also leave it... it doesn't hurt anything, other than throwing a warning in validation

**Comment by dbay24** [comment]
I was pushed in the direction of redundancy for accessibility by some reading I did, I will try to find those articles and what the arguments were for it. I don't think it hurts anything aside from those warnings, and I would rather us have those warnings and the site be slightly more accessible to a wider swath of the population. But in the future it will be something that can be dropped b/c semantic html, and we will just have to discuss when we want to do it.

**Comment by chuckhendo** [comment]
I generally agree with that @dbay24, which is why I wanted to discuss it. The only thing it hurts really would potentially be Willow's credibility; if people use it on their sites and run validation, and our code is returning warnings. 

But accessibility is more than screen reader support; it's browser support too. We drop old browsers all the time, so we may want to determine what our supported screen readers are, and then make sure it works in those

**Comment by dbay24** [comment]
Agreed. I don't think that willow will lose any credibility if we have something specifically addressing accessibility redundancy in the documentation, but I see what you are saying about the software support. I think that being AA compliant will cover most of the screen readers being used, or issues that they encounter. Also, I don't think we have the capacity to establish or curate a list of supported versions of screen readers like we did with browsers.

**Comment by slkennedy** [comment]
Okay so we'll leave these roles in tack for now and I'll update the Willow docs for clarity.  I'll close this issue when those updates are done.
