### ISSUE TITLE
Suggestions for form elements?

### ISSUE THREAD

**Issue by AllThingsSmitty** [unumux/willow#75]
Willow doesn't currently have UI suggestions for form elements, e.g., inputs, radios, checkboxes. If I were creating a web form, is there a base recommendation for how labels, fields, etc. should be positioned in the layout?

**Comment by slkennedy** [comment]
Base styles for forms are coming - they're actually in the [develop branch](https://github.com/unumux/willow/blob/develop/base-elements/_base-elements.scss#L219) just waiting final review.  

Here's notes from the research/standards we developed regarding forms and label.  Probably TMI but maybe not 😄 : 
- Labels should never be in all caps, nor in all lowercase format
- Labels should be above the input field
- Labels should be a maximum of 70 characters
- Group label and field together with appropriate spacing
- Group related information into sections with a header for context. Especially helpful for longer forms to make them less overwhelming.
- Helper text should be used when a label is longer than 70 characters
- Visibly mark optional fields only. Research shows users are more likely to fill out the entire form if you mark optional fields instead of the required fields.
- Don’t ask for information you don’t need
- Make the CTA descriptive of the action that is about to occur.

**Comment by chuckhendo** [comment]
What's our position on "label-less" fields? (Using a placeholder for label or other "creative" approaches)

**Comment by slkennedy** [comment]
We recommend  that a form/input does not use placeholders in lieu of labels. This can cause confusion as the placeholder disappears when a user focuses/types in the input.
